config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "db", to: "users#index"
  get "signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  # get "show", to: "users#index"
  # get "show/:id", to: "users#show"
  # get "edit", to: "users#edit"
  # post "edit", to: "users#update"
  resources :users
  # get "edit", to: "users#edit"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully."
      redirect_to db_path
    else
      flash[:alert] = "Please check the login credentials."
      # render "new"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Object successfully created"
      redirect_to root_path
    else
      flash[:error] = "Something went wrong"
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

	 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
	<%= render partial: 'shared/flash' %>
	<div class="container">
    <%= yield %>
	</div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Home</h1>


<%= link_to 'SignUp', signup_path %><br><br>
<%= link_to 'Login', login_path %><br><br>

<%= link_to 'Show data', db_path%>

app/views/shared/_flash.html.erb
<% if flash[:success] %>
<div class="alert alert-info", role="alert">
<%= flash[:success] %>
</div>
<%end%>

<% if flash[:error] %>
<div class="alert alert-warning", role="alert">
<%= flash[:error] %>
</div>
<%end%>

<% if flash[:notice] %>
<div class="alert alert-info", role="alert">
<%= flash[:notice] %>
</div>
<%end%>

<% if flash[:alert] %>
<div class="alert alert-warning", role="alert">
<%= flash[:alert] %>
</div>
<%end%>

app/views/users/_form.html.erb
<%= form_with model: user do |form|%>

<div class="mb-5">
	<%= form.label :username%>
	<%= form.text_field :username, class:"form-control" %>
</div>

<div class="mb-5">
	<%= form.label :password%>
	<%= form.password_field :password, class:"form-control" %>
</div>

<div class="mb-5">
	<%= form.submit "Sign Up", class:"btn btn-primary"%>
</div>

<%end%>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<ul>
<li><%= render 'form', user: @user %></li>
</ul>

app/views/users/index.html.erb
<% @user.each do |a|%>
<a href="/users/<%= a.id %>">
<%= a.username%> <br>
</a>
<%end%>

<%= link_to "New User", new_user_path %> <br><br>

app/views/users/new.html.erb
<h1>Sign Up </h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h4><%= @user.username%></h4>

<p><%= @user.password_digest %></p>

<%= link_to 'edit', edit_user_path %>
<%= link_to "Destroy", user_path(@user), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>